### PR TITLE
Implementation of private API for File Reports

### PR DESCRIPTION
**Pull request by keithjjones**
Should be a good basis for completing issue #18 

I will add the other private API functions as I get time.  They will be on this pull request unless you merge them before I finish.

### CODE REVIEW

**Comment by keithjjones** [comment]
I think that was the last of the heavy lifting.  Most of the private API should have been added.  If you have ideas on how to check your key, I'll add that.

**Comment by keithjjones** [comment]
Do you plan on testing an accepting this?

**Comment by keithjjones** [comment]
The bug identified above is for that particular MD5 hash.  I am not sure why it is different than 1000's of others I have run through the library.

**Comment by leechristensen** [comment]
@Genbox Is there anything blocking accepting this pull? I can help test if need be.

**Comment by Genbox** [comment]
This contains multiple changes that should be separated.
The license has changed to MIT as well.

I will close this for now. Feel free to implement the private API according to #18 and I will add you to the contributors list.

**Comment by keithjjones** [comment]
Unfortunately this is so old I don't have access to a private key anymore to do any more work on it.  Also, I switched to working on the python version of this.

**Comment by Genbox** [comment]
Same here with the API key - the shut down the API key we were using about a year back. I really appreciate your contribution, and if I ever get hold of an API key again, I will certainly take a look at the work you did and attribute you accordingly.

**Pull request closed without merging**
