### PR TITLE
Bug fixes for domain reports

### PR DESCRIPTION
**Pull request by keithjjones**
Fixed a bug in domain reports concerning the WhoIsDateTime.  This should fix Issue #19.

### CODE REVIEW

**Comment by Genbox** [comment]
Hi Keith,

Thanks for making this pull request. Unfortunately it contains too many changes that are not relevant. A couple of things stands out:

1. The unit test with the "." domain is not wrong, it is a bug in the VT API that I've reported a year ago, but has not been fixed yet. Thanks to you, I've added a comment that explains that.

2. You added explicit "DeserializeAs" to many properties, however, by default, Restsharp guesses the name, leaving some wiggle-room for small changes, such as if they suddenly decide to call "detected_urls" for DetectedURLs", it still works. However, thanks to you, the issue with subdomains (which they now call "domain_siblings") was fixed.

3. You added yourself as author and owner, which is untrue. You are indeed a contributor, which you will be credited for.

I've added the relevant code to the source control and mentioned you as a contributor, thanks for helping out.

**Comment by Genbox** [comment]
Thanks for reporting this. See #19 for response.

**Comment by keithjjones** [comment]
No problem.  Thanks for doing the hard work of getting most of this written.  I will check into your changes later this week to see if all the bugs have disappeared. I found the domain reports are the hardest to match up with VT.  I wish they had a schema I could reference.

You may want to add the automated NuGet generation that I added.  NuGet information is not in the repository.  Also, doing something about an App.config that a developer may put their key into would be a good idea. You don't want them accidentally uploading their key.  I am actively working with this library and I'm sure I'll find more to change or add in the weeks to come.  Keep an eye out for pull requests if I find anything.

I guess "relevant" changes depends on who is using the library.  All of the changes I submitted were required for projects I am working on that use the library.  They are definitely relevant for me.

Thanks!

**Comment by keithjjones** [comment]
My copyright information in the assembly is within the scope of a contributor and of the Apache license you chose to use.  Please add.  If you are talking about "Owner" and "Contributor" regarding the .nuspec file, I agree with you - you are the owner and author of the NuGet file you upload to nuget.org, but you didn't have a .nuspec file in the repository so I had to make something so I could test if the changes and bugfixes worked as intended.  If you include the .nuspec the way you want it in the repository, I will use yours.

**Comment by keithjjones** [comment]
I would suggest adding the extra domain report test I wrote.  That was the method I used to discover the domain report parsing exception bug.

**Pull request closed without merging**
